FROM node:20.12-slim

WORKDIR /app
COPY ./skyvern-frontend /app
COPY ./entrypoint-skyvernui.sh /app/entrypoint-skyvernui.sh
RUN npm install

# Set the API base URL from an argument or default to localhost
ARG API_BASE_URL_ARG=https://skyvernserver.teamcat.app/api/v1
ENV VITE_API_BASE_URL=$API_BASE_URL_ARG
# Derive WSS from API base URL
ENV VITE_WSS_BASE_URL=${API_BASE_URL_ARG/https/wss}
ENV VITE_ARTIFACT_API_BASE_URL=http://localhost:9090

CMD [ "/bin/bash", "/app/entrypoint-skyvernui.sh" ]

